name = "ElasticSearch"
uuid = "0d0b3e3c-8241-4271-8221-92a6a704d6fd"
authors = ["lotcher <cb229435444@outlook.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
